/*
 * Recipe database for the Family Dinner Planner.
 *
 * Rules baked into the data:
 *   - No seafood (none included).
 *   - No berries (none included).
 *   - Cuisines: mexican, italian, american, ricebowl, mediterranean, asian.
 *   - kidFriendly: meals a 2-year-old (Wesley) will happily eat, no separate cooking.
 *   - blackstone: works great on a flattop / Blackstone griddle.
 *   - ifTip: an easy way to cut calories for mom's intermittent fasting.
 *
 * Ingredient categories drive the grocery-list grouping:
 *   produce, meat, dairy, pantry, bakery, frozen.
 * staple:true marks common things you likely already have (oil, salt, etc.) —
 * they still show up so you can verify, but are grouped under "Pantry staples".
 */

const CUISINE_LABELS = {
  mexican: "Mexican",
  italian: "Italian",
  american: "American",
  ricebowl: "Rice Bowls",
  mediterranean: "Mediterranean",
  asian: "Asian",
};

const CATEGORY_ORDER = ["produce", "meat", "dairy", "frozen", "bakery", "pantry"];
const CATEGORY_LABELS = {
  produce: "Produce",
  meat: "Meat & Protein",
  dairy: "Dairy & Eggs",
  frozen: "Frozen",
  bakery: "Bakery",
  pantry: "Pantry staples",
};

const RECIPES = [
  // ---------------- MEXICAN ----------------
  {
    id: "beef-burrito-bowls",
    name: "Beef Burrito Bowls",
    cuisine: "mexican",
    time: 35,
    servings: 4,
    calories: 620,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Skip the rice and double the lettuce/pico for a burrito salad — saves ~200 cal.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "black beans", qty: 1, unit: "can", category: "pantry" },
      { item: "shredded cheddar", qty: 1, unit: "cup", category: "dairy" },
      { item: "romaine lettuce", qty: 1, unit: "head", category: "produce" },
      { item: "roma tomatoes", qty: 2, unit: "", category: "produce" },
      { item: "lime", qty: 1, unit: "", category: "produce" },
      { item: "taco seasoning", qty: 1, unit: "packet", category: "pantry" },
      { item: "sour cream", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "salt", qty: 1, unit: "pinch", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice per package directions; fluff and stir in a squeeze of lime and a pinch of salt.",
      "Brown the ground beef over medium-high, drain, then stir in taco seasoning + a splash of water. Simmer 3–4 min.",
      "Warm the black beans in a small pot.",
      "Dice tomatoes and chop romaine.",
      "Build bowls: rice, beef, beans, cheese, lettuce, tomato, and a dollop of sour cream.",
    ],
  },
  {
    id: "chicken-fajitas",
    name: "Blackstone Chicken Fajitas",
    cuisine: "mexican",
    time: 30,
    servings: 4,
    calories: 540,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Serve over shredded lettuce instead of tortillas; mom keeps the chicken + peppers.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "bell peppers", qty: 3, unit: "", category: "produce" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "flour tortillas", qty: 8, unit: "", category: "bakery" },
      { item: "shredded cheese", qty: 1, unit: "cup", category: "dairy" },
      { item: "fajita seasoning", qty: 2, unit: "tbsp", category: "pantry" },
      { item: "lime", qty: 1, unit: "", category: "produce" },
      { item: "sour cream", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Slice chicken, peppers, and onion into thin strips.",
      "Heat the Blackstone (or large skillet) to high with oil.",
      "Cook chicken with fajita seasoning until browned, ~6 min; push to a cooler zone.",
      "Sear peppers and onion until charred-tender, ~5 min. Squeeze lime over everything.",
      "Warm tortillas on the griddle. Serve with cheese and sour cream.",
    ],
  },
  {
    id: "beef-enchilada-bake",
    name: "Beef Enchilada Bake",
    cuisine: "mexican",
    time: 50,
    servings: 6,
    calories: 580,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Have one portion with extra salsa instead of cheese on top to trim ~150 cal.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "corn tortillas", qty: 12, unit: "", category: "bakery" },
      { item: "red enchilada sauce", qty: 2, unit: "cans", category: "pantry" },
      { item: "black beans", qty: 1, unit: "can", category: "pantry" },
      { item: "shredded Mexican cheese", qty: 2, unit: "cups", category: "dairy" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "cumin", qty: 1, unit: "tsp", category: "pantry", staple: true },
      { item: "salt", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Preheat oven to 375°F.",
      "Brown beef with diced onion and cumin; drain. Stir in beans and half the enchilada sauce.",
      "Layer in a baking dish: sauce, tortillas, beef mix, cheese. Repeat, ending with cheese.",
      "Cover with foil, bake 25 min; uncover and bake 10 more until bubbly.",
      "Rest 5 min before cutting.",
    ],
  },

  // ---------------- ITALIAN ----------------
  {
    id: "spaghetti-meat-sauce",
    name: "Spaghetti with Meat Sauce",
    cuisine: "italian",
    time: 40,
    servings: 5,
    calories: 600,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Swap half the pasta for zucchini noodles, or skip noodles and eat the sauce over sautéed zucchini.",
    ingredients: [
      { item: "spaghetti", qty: 1, unit: "lb", category: "pantry" },
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "marinara sauce", qty: 1, unit: "jar", category: "pantry" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "parmesan", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "italian seasoning", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Boil spaghetti until al dente; reserve a splash of pasta water.",
      "Sauté diced onion and garlic in oil until soft.",
      "Add beef, brown and drain. Stir in marinara + Italian seasoning; simmer 10 min.",
      "Toss pasta with sauce, loosening with pasta water if needed.",
      "Top with parmesan.",
    ],
  },
  {
    id: "chicken-parm-casserole",
    name: "Chicken Parmesan Casserole",
    cuisine: "italian",
    time: 55,
    servings: 6,
    calories: 640,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Serve mom's portion over a bed of steamed broccoli instead of pasta.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "penne pasta", qty: 12, unit: "oz", category: "pantry" },
      { item: "marinara sauce", qty: 1, unit: "jar", category: "pantry" },
      { item: "mozzarella", qty: 2, unit: "cups", category: "dairy" },
      { item: "parmesan", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "panko breadcrumbs", qty: 1, unit: "cup", category: "pantry" },
      { item: "eggs", qty: 2, unit: "", category: "dairy" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Preheat oven to 400°F and boil penne until just shy of done.",
      "Cut chicken into bite-size pieces, dip in beaten egg then panko, and pan-fry in oil until golden.",
      "Mix pasta with marinara in a baking dish; fold in the chicken.",
      "Top with mozzarella and parmesan.",
      "Bake 18–20 min until cheese is melted and golden.",
    ],
  },
  {
    id: "sausage-pepper-pasta",
    name: "Sausage & Pepper Pasta",
    cuisine: "italian",
    time: 35,
    servings: 5,
    calories: 590,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Use chicken sausage and serve over a smaller scoop of pasta with extra peppers.",
    ingredients: [
      { item: "italian sausage", qty: 1, unit: "lb", category: "meat" },
      { item: "rigatoni", qty: 1, unit: "lb", category: "pantry" },
      { item: "bell peppers", qty: 2, unit: "", category: "produce" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "marinara sauce", qty: 1, unit: "jar", category: "pantry" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "parmesan", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Boil rigatoni until al dente.",
      "On the flattop or skillet, brown sliced sausage; add peppers, onion, and garlic and cook until soft.",
      "Stir in marinara and simmer 5 min.",
      "Toss with pasta and finish with parmesan.",
    ],
  },

  // ---------------- AMERICAN ----------------
  {
    id: "smash-burgers",
    name: "Blackstone Smash Burgers",
    cuisine: "american",
    time: 30,
    servings: 4,
    calories: 680,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Go bunless (lettuce wrap) and skip the cheese to cut ~250 cal.",
    ingredients: [
      { item: "ground beef (80/20)", qty: 1.5, unit: "lb", category: "meat" },
      { item: "hamburger buns", qty: 4, unit: "", category: "bakery" },
      { item: "american cheese", qty: 4, unit: "slices", category: "dairy" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "lettuce", qty: 4, unit: "leaves", category: "produce" },
      { item: "tomato", qty: 1, unit: "", category: "produce" },
      { item: "pickles", qty: 1, unit: "jar", category: "pantry" },
      { item: "salt", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Form beef into loose 4 oz balls.",
      "Get the Blackstone screaming hot. Smash each ball flat with a spatula and salt.",
      "Cook 2–3 min until edges crisp, flip, add cheese, cook 1 more min.",
      "Toast buns on the griddle.",
      "Build with onion, lettuce, tomato, and pickles.",
    ],
  },
  {
    id: "bbq-chicken-sheetpan",
    name: "BBQ Chicken & Veggie Sheet Pan",
    cuisine: "american",
    time: 45,
    servings: 4,
    calories: 520,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Use half the BBQ sauce (sugar) and load up on the roasted veggies.",
    ingredients: [
      { item: "chicken thighs", qty: 2, unit: "lb", category: "meat" },
      { item: "baby potatoes", qty: 1.5, unit: "lb", category: "produce" },
      { item: "broccoli", qty: 1, unit: "head", category: "produce" },
      { item: "bbq sauce", qty: 0.75, unit: "cup", category: "pantry" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
      { item: "salt", qty: 1, unit: "tsp", category: "pantry", staple: true },
      { item: "pepper", qty: 0.5, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Preheat oven to 425°F.",
      "Halve potatoes, toss with oil, salt, pepper; roast 15 min.",
      "Add chicken (brushed with BBQ sauce) and broccoli to the pan.",
      "Roast 20–25 min until chicken hits 165°F, brushing more sauce halfway.",
    ],
  },
  {
    id: "loaded-baked-potato-bar",
    name: "Loaded Baked Potato Bar",
    cuisine: "american",
    time: 60,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Top with extra steamed broccoli + a little cheese; go light on butter and sour cream.",
    ingredients: [
      { item: "russet potatoes", qty: 4, unit: "", category: "produce" },
      { item: "bacon", qty: 6, unit: "slices", category: "meat" },
      { item: "shredded cheddar", qty: 1, unit: "cup", category: "dairy" },
      { item: "sour cream", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "green onions", qty: 1, unit: "bunch", category: "produce" },
      { item: "broccoli", qty: 1, unit: "head", category: "produce" },
      { item: "butter", qty: 2, unit: "tbsp", category: "dairy", staple: true },
    ],
    steps: [
      "Preheat oven to 400°F. Pierce potatoes, rub with oil/salt, bake 50–60 min.",
      "Cook bacon until crisp; crumble.",
      "Steam broccoli until tender.",
      "Split potatoes and set out all toppings so everyone builds their own.",
    ],
  },

  // ---------------- RICE BOWLS ----------------
  {
    id: "teriyaki-chicken-bowl",
    name: "Teriyaki Chicken Rice Bowl",
    cuisine: "ricebowl",
    time: 35,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Use cauliflower rice for mom and a low-sugar teriyaki — cuts ~200 cal.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "teriyaki sauce", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "broccoli", qty: 1, unit: "head", category: "produce" },
      { item: "carrots", qty: 2, unit: "", category: "produce" },
      { item: "sesame seeds", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "vegetable oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Dice chicken and sear on the flattop/skillet in oil until cooked through.",
      "Add teriyaki sauce and let it glaze the chicken, ~2 min.",
      "Steam or griddle the broccoli and carrots.",
      "Build bowls: rice, chicken, veggies, sprinkle of sesame seeds.",
    ],
  },
  {
    id: "korean-beef-bowl",
    name: "Korean Beef Bowl",
    cuisine: "ricebowl",
    time: 25,
    servings: 4,
    calories: 590,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Lower the brown sugar by half and serve over cauliflower rice.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "soy sauce", qty: 0.25, unit: "cup", category: "pantry" },
      { item: "brown sugar", qty: 3, unit: "tbsp", category: "pantry", staple: true },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "green onions", qty: 1, unit: "bunch", category: "produce" },
      { item: "sesame oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "ginger", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Brown beef with garlic and ginger; drain.",
      "Stir in soy sauce, brown sugar, and sesame oil; simmer 3 min.",
      "Serve over rice, topped with sliced green onions.",
    ],
  },
  {
    id: "carnitas-rice-bowl",
    name: "Carnitas Rice Bowl",
    cuisine: "ricebowl",
    time: 40,
    servings: 4,
    calories: 610,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Skip the rice, double the cabbage slaw, and add extra lime + cilantro.",
    ingredients: [
      { item: "pork shoulder (or pre-cooked carnitas)", qty: 1.5, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "black beans", qty: 1, unit: "can", category: "pantry" },
      { item: "cabbage", qty: 0.5, unit: "head", category: "produce" },
      { item: "lime", qty: 2, unit: "", category: "produce" },
      { item: "cilantro", qty: 1, unit: "bunch", category: "produce" },
      { item: "cotija cheese", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "cumin", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice; stir in lime juice and chopped cilantro.",
      "Crisp the carnitas on the flattop until edges are golden.",
      "Warm black beans with a pinch of cumin.",
      "Shred cabbage and toss with lime juice for a quick slaw.",
      "Build bowls: rice, carnitas, beans, slaw, cotija.",
    ],
  },

  // ---------------- A FEW MORE FOR VARIETY ----------------
  {
    id: "chicken-quesadillas",
    name: "Blackstone Chicken Quesadillas",
    cuisine: "mexican",
    time: 25,
    servings: 4,
    calories: 550,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Make mom's as a single open-faced tortilla with extra chicken, less cheese.",
    ingredients: [
      { item: "chicken breast", qty: 1, unit: "lb", category: "meat" },
      { item: "flour tortillas", qty: 8, unit: "", category: "bakery" },
      { item: "shredded Mexican cheese", qty: 2, unit: "cups", category: "dairy" },
      { item: "bell pepper", qty: 1, unit: "", category: "produce" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "taco seasoning", qty: 1, unit: "tbsp", category: "pantry" },
      { item: "salsa", qty: 1, unit: "jar", category: "pantry" },
    ],
    steps: [
      "Dice and cook chicken with taco seasoning on the flattop.",
      "Sauté peppers and onion alongside.",
      "Build quesadillas: tortilla, cheese, chicken/veg, cheese, tortilla.",
      "Griddle until golden and crispy on both sides. Cut into wedges, serve with salsa.",
    ],
  },
  {
    id: "philly-cheesesteak-bowl",
    name: "Philly Cheesesteak Rice Bowl",
    cuisine: "ricebowl",
    time: 30,
    servings: 4,
    calories: 600,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Swap rice for cauliflower rice and use provolone sparingly.",
    ingredients: [
      { item: "thin-sliced steak (or shaved beef)", qty: 1.25, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "bell peppers", qty: 2, unit: "", category: "produce" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "provolone cheese", qty: 4, unit: "slices", category: "dairy" },
      { item: "worcestershire sauce", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Sear the beef on a hot flattop; season with salt and Worcestershire.",
      "Add peppers and onion; cook until soft and a little charred.",
      "Lay provolone over the meat to melt, then chop it all together.",
      "Serve over rice.",
    ],
  },
  {
    id: "chicken-alfredo",
    name: "Chicken Alfredo",
    cuisine: "italian",
    time: 35,
    servings: 4,
    calories: 720,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Serve mom's sauce over steamed broccoli or a small portion of pasta with extra chicken.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "fettuccine", qty: 12, unit: "oz", category: "pantry" },
      { item: "heavy cream", qty: 1, unit: "cup", category: "dairy" },
      { item: "parmesan", qty: 1, unit: "cup", category: "dairy" },
      { item: "butter", qty: 3, unit: "tbsp", category: "dairy", staple: true },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "broccoli", qty: 1, unit: "head", category: "produce" },
    ],
    steps: [
      "Boil fettuccine; add broccoli in the last 3 min.",
      "Season and pan-sear sliced chicken until cooked; set aside.",
      "Melt butter, sauté garlic, add cream and parmesan; simmer until thick.",
      "Toss pasta and broccoli in sauce, top with chicken.",
    ],
  },
  {
    id: "sloppy-joes",
    name: "Sloppy Joes",
    cuisine: "american",
    time: 30,
    servings: 5,
    calories: 540,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Serve the meat over a baked potato or greens instead of a bun.",
    ingredients: [
      { item: "ground beef", qty: 1.25, unit: "lb", category: "meat" },
      { item: "hamburger buns", qty: 5, unit: "", category: "bakery" },
      { item: "ketchup", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "tomato sauce", qty: 1, unit: "can", category: "pantry" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "bell pepper", qty: 1, unit: "", category: "produce" },
      { item: "brown sugar", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "worcestershire sauce", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Brown beef with diced onion and pepper; drain.",
      "Stir in ketchup, tomato sauce, brown sugar, and Worcestershire.",
      "Simmer 10 min until thick.",
      "Spoon onto toasted buns.",
    ],
  },
  {
    id: "taco-tuesday",
    name: "Classic Beef Tacos",
    cuisine: "mexican",
    time: 25,
    servings: 4,
    calories: 520,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Use lettuce cups instead of shells and skip the cheese.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "taco shells", qty: 12, unit: "", category: "bakery" },
      { item: "taco seasoning", qty: 1, unit: "packet", category: "pantry" },
      { item: "shredded cheddar", qty: 1, unit: "cup", category: "dairy" },
      { item: "lettuce", qty: 0.5, unit: "head", category: "produce" },
      { item: "roma tomatoes", qty: 2, unit: "", category: "produce" },
      { item: "sour cream", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "salsa", qty: 1, unit: "jar", category: "pantry" },
    ],
    steps: [
      "Brown beef, drain, add taco seasoning + water; simmer 4 min.",
      "Warm taco shells in the oven.",
      "Chop lettuce and tomatoes.",
      "Set out a taco bar and let everyone build their own.",
    ],
  },
  {
    id: "pesto-chicken-pasta",
    name: "Pesto Chicken Pasta",
    cuisine: "italian",
    time: 30,
    servings: 4,
    calories: 610,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Use half pasta, half sautéed zucchini ribbons and extra chicken.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "penne pasta", qty: 12, unit: "oz", category: "pantry" },
      { item: "basil pesto", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "cherry tomatoes", qty: 1, unit: "cup", category: "produce" },
      { item: "parmesan", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Boil penne; reserve a splash of pasta water.",
      "Season and cook diced chicken in oil until golden.",
      "Toss pasta with pesto, chicken, and halved tomatoes, loosening with pasta water.",
      "Finish with parmesan.",
    ],
  },

  // ================= EXPANDED LIBRARY =================

  // ---------------- MEXICAN ----------------
  {
    id: "carne-asada-tacos",
    name: "Blackstone Carne Asada Tacos",
    cuisine: "mexican",
    time: 35,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Use lettuce cups instead of tortillas and pile on extra grilled onion.",
    ingredients: [
      { item: "flank or skirt steak", qty: 1.5, unit: "lb", category: "meat" },
      { item: "corn tortillas", qty: 12, unit: "", category: "bakery" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "cilantro", qty: 1, unit: "bunch", category: "produce" },
      { item: "lime", qty: 2, unit: "", category: "produce" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "cumin", qty: 1, unit: "tsp", category: "pantry", staple: true },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Marinate steak 20 min in lime juice, minced garlic, cumin, oil, and salt.",
      "Sear on a screaming-hot flattop, 3–4 min per side; rest, then chop.",
      "Char the tortillas on the griddle.",
      "Top with steak, diced onion, and cilantro with a squeeze of lime.",
    ],
  },
  {
    id: "chicken-tinga-tacos",
    name: "Chicken Tinga Tacos",
    cuisine: "mexican",
    time: 35,
    servings: 4,
    calories: 520,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Skip the tortillas and serve the tinga over shredded cabbage as a bowl.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "corn tortillas", qty: 12, unit: "", category: "bakery" },
      { item: "fire-roasted diced tomatoes", qty: 1, unit: "can", category: "pantry" },
      { item: "chipotle in adobo", qty: 2, unit: "tbsp", category: "pantry" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "cotija cheese", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "lime", qty: 1, unit: "", category: "produce" },
      { item: "cumin", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Simmer chicken in water 15 min, then shred.",
      "Blend tomatoes, chipotle, and a little onion into a sauce.",
      "Sauté the rest of the onion, add sauce and chicken, simmer 8 min.",
      "Pile into warm tortillas; top with cotija and lime.",
    ],
  },
  {
    id: "loaded-beef-nachos",
    name: "Loaded Beef Nachos",
    cuisine: "mexican",
    time: 30,
    servings: 4,
    calories: 640,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Build a personal plate with extra beans and salsa, light cheese; skip the sour cream.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "tortilla chips", qty: 1, unit: "bag", category: "pantry" },
      { item: "black beans", qty: 1, unit: "can", category: "pantry" },
      { item: "shredded Mexican cheese", qty: 2, unit: "cups", category: "dairy" },
      { item: "roma tomatoes", qty: 2, unit: "", category: "produce" },
      { item: "jalapeño", qty: 1, unit: "", category: "produce" },
      { item: "sour cream", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "taco seasoning", qty: 1, unit: "packet", category: "pantry" },
    ],
    steps: [
      "Preheat oven to 400°F. Brown beef with taco seasoning; drain.",
      "Spread chips on a sheet pan; scatter beef, beans, and cheese.",
      "Bake 8–10 min until cheese melts.",
      "Top with diced tomato, jalapeño, and a drizzle of sour cream.",
    ],
  },
  {
    id: "chicken-burrito-bowls",
    name: "Cilantro-Lime Chicken Burrito Bowls",
    cuisine: "mexican",
    time: 35,
    servings: 4,
    calories: 580,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Swap rice for extra romaine and load up on pico for a low-cal bowl.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "black beans", qty: 1, unit: "can", category: "pantry" },
      { item: "corn", qty: 1, unit: "can", category: "pantry" },
      { item: "lime", qty: 2, unit: "", category: "produce" },
      { item: "cilantro", qty: 1, unit: "bunch", category: "produce" },
      { item: "shredded cheese", qty: 1, unit: "cup", category: "dairy" },
      { item: "taco seasoning", qty: 1, unit: "tbsp", category: "pantry" },
    ],
    steps: [
      "Cook rice; stir in lime juice and chopped cilantro.",
      "Season diced chicken with taco seasoning and sear on the flattop.",
      "Warm beans and corn together.",
      "Build bowls: rice, chicken, beans, corn, cheese, extra lime.",
    ],
  },
  {
    id: "pork-carnitas-tacos",
    name: "Crispy Pork Carnitas Tacos",
    cuisine: "mexican",
    time: 40,
    servings: 4,
    calories: 590,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Serve in lettuce cups with extra onion and cilantro instead of tortillas.",
    ingredients: [
      { item: "pork shoulder (or pre-cooked carnitas)", qty: 1.5, unit: "lb", category: "meat" },
      { item: "corn tortillas", qty: 12, unit: "", category: "bakery" },
      { item: "white onion", qty: 1, unit: "", category: "produce" },
      { item: "cilantro", qty: 1, unit: "bunch", category: "produce" },
      { item: "lime", qty: 2, unit: "", category: "produce" },
      { item: "orange", qty: 1, unit: "", category: "produce" },
      { item: "cumin", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Toss pork with cumin, salt, and orange juice.",
      "Crisp on the flattop until edges are deeply golden.",
      "Warm tortillas on the griddle.",
      "Top with carnitas, diced onion, cilantro, and lime.",
    ],
  },
  {
    id: "chicken-taquitos",
    name: "Baked Chicken Taquitos",
    cuisine: "mexican",
    time: 35,
    servings: 4,
    calories: 530,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Have a few with a big side salad instead of cheese dip to keep it light.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "corn tortillas", qty: 12, unit: "", category: "bakery" },
      { item: "cream cheese", qty: 4, unit: "oz", category: "dairy" },
      { item: "shredded Mexican cheese", qty: 1.5, unit: "cups", category: "dairy" },
      { item: "salsa verde", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "cumin", qty: 1, unit: "tsp", category: "pantry", staple: true },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Preheat oven to 425°F. Cook and shred chicken.",
      "Mix chicken with cream cheese, shredded cheese, salsa verde, and cumin.",
      "Roll filling tightly in warmed tortillas; place seam-down on a sheet pan.",
      "Brush with oil and bake 15–18 min until crisp.",
    ],
  },
  {
    id: "beef-taco-skillet",
    name: "One-Pan Beef Taco Skillet",
    cuisine: "mexican",
    time: 30,
    servings: 5,
    calories: 560,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Skip the rice in the skillet and serve over shredded lettuce instead.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1, unit: "cup (dry)", category: "pantry" },
      { item: "black beans", qty: 1, unit: "can", category: "pantry" },
      { item: "diced tomatoes", qty: 1, unit: "can", category: "pantry" },
      { item: "shredded cheddar", qty: 1, unit: "cup", category: "dairy" },
      { item: "bell pepper", qty: 1, unit: "", category: "produce" },
      { item: "taco seasoning", qty: 1, unit: "packet", category: "pantry" },
    ],
    steps: [
      "Brown beef with diced pepper; drain.",
      "Stir in taco seasoning, rice, beans, tomatoes, and 1.5 cups water.",
      "Cover and simmer 18–20 min until rice is tender.",
      "Top with cheese, cover off heat until melted.",
    ],
  },
  {
    id: "chicken-tortilla-soup",
    name: "Chicken Tortilla Soup",
    cuisine: "mexican",
    time: 40,
    servings: 5,
    calories: 420,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Already light — skip the cheese and tortilla strips and add extra lime.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "chicken broth", qty: 6, unit: "cups", category: "pantry" },
      { item: "fire-roasted diced tomatoes", qty: 1, unit: "can", category: "pantry" },
      { item: "black beans", qty: 1, unit: "can", category: "pantry" },
      { item: "corn", qty: 1, unit: "can", category: "pantry" },
      { item: "tortilla chips", qty: 1, unit: "bag", category: "pantry" },
      { item: "lime", qty: 1, unit: "", category: "produce" },
      { item: "cumin", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Simmer chicken in broth with tomatoes and cumin, 15 min; shred and return.",
      "Add beans and corn; simmer 10 more min.",
      "Finish with a squeeze of lime.",
      "Serve topped with crushed tortilla chips.",
    ],
  },
  {
    id: "ground-beef-chimichangas",
    name: "Baked Beef Chimichangas",
    cuisine: "mexican",
    time: 40,
    servings: 4,
    calories: 610,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Make mom's open-faced as a soft burrito bowl with extra beans, no frying.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "large flour tortillas", qty: 6, unit: "", category: "bakery" },
      { item: "refried beans", qty: 1, unit: "can", category: "pantry" },
      { item: "shredded Mexican cheese", qty: 1.5, unit: "cups", category: "dairy" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "taco seasoning", qty: 1, unit: "packet", category: "pantry" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Preheat oven to 425°F. Brown beef with onion and taco seasoning.",
      "Spread refried beans on tortillas; add beef and cheese.",
      "Fold into tight bundles, place seam-down, brush with oil.",
      "Bake 18–20 min until golden and crisp.",
    ],
  },

  // ---------------- ITALIAN ----------------
  {
    id: "chicken-piccata",
    name: "Chicken Piccata",
    cuisine: "italian",
    time: 35,
    servings: 4,
    calories: 520,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Serve over steamed zucchini or broccoli instead of pasta.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "flour", qty: 0.5, unit: "cup", category: "pantry", staple: true },
      { item: "lemon", qty: 2, unit: "", category: "produce" },
      { item: "capers", qty: 2, unit: "tbsp", category: "pantry" },
      { item: "chicken broth", qty: 1, unit: "cup", category: "pantry" },
      { item: "butter", qty: 3, unit: "tbsp", category: "dairy", staple: true },
      { item: "parsley", qty: 1, unit: "small bunch", category: "produce" },
      { item: "spaghetti", qty: 12, unit: "oz", category: "pantry" },
    ],
    steps: [
      "Pound chicken thin, dredge in flour, sear in butter until golden; set aside.",
      "Deglaze pan with broth and lemon juice; stir in capers.",
      "Return chicken, simmer 5 min; finish with butter and parsley.",
      "Serve over spaghetti.",
    ],
  },
  {
    id: "beef-bolognese",
    name: "Beef Bolognese",
    cuisine: "italian",
    time: 50,
    servings: 5,
    calories: 600,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Serve the sauce over sautéed zucchini ribbons instead of pasta.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "pappardelle or tagliatelle", qty: 1, unit: "lb", category: "pantry" },
      { item: "crushed tomatoes", qty: 1, unit: "can", category: "pantry" },
      { item: "carrots", qty: 2, unit: "", category: "produce" },
      { item: "celery", qty: 2, unit: "stalks", category: "produce" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "milk", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "parmesan", qty: 0.5, unit: "cup", category: "dairy" },
    ],
    steps: [
      "Finely dice carrot, celery, and onion; sauté until soft.",
      "Add beef and brown; drain excess fat.",
      "Stir in tomatoes and milk; simmer 25–30 min until thick.",
      "Toss with cooked pasta and finish with parmesan.",
    ],
  },
  {
    id: "italian-meatball-subs",
    name: "Italian Meatball Subs",
    cuisine: "italian",
    time: 40,
    servings: 4,
    calories: 660,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Skip the roll and serve meatballs over zucchini or a salad.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "sub rolls", qty: 4, unit: "", category: "bakery" },
      { item: "marinara sauce", qty: 1, unit: "jar", category: "pantry" },
      { item: "mozzarella", qty: 1.5, unit: "cups", category: "dairy" },
      { item: "parmesan", qty: 0.25, unit: "cup", category: "dairy" },
      { item: "breadcrumbs", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "egg", qty: 1, unit: "", category: "dairy" },
      { item: "garlic", qty: 2, unit: "cloves", category: "produce" },
    ],
    steps: [
      "Mix beef, breadcrumbs, egg, parmesan, and garlic; roll into meatballs.",
      "Brown meatballs, then simmer in marinara 15 min.",
      "Fill rolls with meatballs and sauce; top with mozzarella.",
      "Broil 2–3 min until cheese is bubbly.",
    ],
  },
  {
    id: "creamy-tuscan-chicken",
    name: "Creamy Tuscan Chicken",
    cuisine: "italian",
    time: 35,
    servings: 4,
    calories: 580,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Use half-and-half instead of cream and serve over greens, not pasta.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "heavy cream", qty: 1, unit: "cup", category: "dairy" },
      { item: "spinach", qty: 4, unit: "cups", category: "produce" },
      { item: "sun-dried tomatoes", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "parmesan", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "penne pasta", qty: 12, unit: "oz", category: "pantry" },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Sear seasoned chicken until cooked; set aside and slice.",
      "Sauté garlic, add cream, parmesan, and sun-dried tomatoes; simmer.",
      "Stir in spinach until wilted; return chicken.",
      "Serve over penne.",
    ],
  },
  {
    id: "sausage-gnocchi",
    name: "Sausage & Tomato Gnocchi",
    cuisine: "italian",
    time: 30,
    servings: 4,
    calories: 610,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Halve the gnocchi and bulk it up with extra spinach and sausage.",
    ingredients: [
      { item: "italian sausage", qty: 1, unit: "lb", category: "meat" },
      { item: "potato gnocchi", qty: 1, unit: "lb", category: "pantry" },
      { item: "crushed tomatoes", qty: 1, unit: "can", category: "pantry" },
      { item: "spinach", qty: 3, unit: "cups", category: "produce" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "parmesan", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Brown sausage with garlic; break into crumbles.",
      "Add tomatoes and simmer 8 min.",
      "Stir in gnocchi and 0.5 cup water; cook 4–5 min until tender.",
      "Fold in spinach until wilted; top with parmesan.",
    ],
  },
  {
    id: "chicken-marsala",
    name: "Chicken Marsala",
    cuisine: "italian",
    time: 40,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Serve over mashed cauliflower or greens instead of pasta.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "mushrooms", qty: 8, unit: "oz", category: "produce" },
      { item: "marsala wine (or chicken broth)", qty: 0.75, unit: "cup", category: "pantry" },
      { item: "flour", qty: 0.5, unit: "cup", category: "pantry", staple: true },
      { item: "butter", qty: 3, unit: "tbsp", category: "dairy", staple: true },
      { item: "garlic", qty: 2, unit: "cloves", category: "produce" },
      { item: "egg noodles", qty: 12, unit: "oz", category: "pantry" },
    ],
    steps: [
      "Pound chicken thin, dredge in flour, and sear in butter; set aside.",
      "Sauté mushrooms and garlic until browned.",
      "Add marsala, scrape the pan, and simmer to reduce.",
      "Return chicken to coat; serve over egg noodles.",
    ],
  },
  {
    id: "caprese-chicken",
    name: "Blackstone Caprese Chicken",
    cuisine: "italian",
    time: 30,
    servings: 4,
    calories: 480,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Already light — skip the bread side and add a big salad.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "fresh mozzarella", qty: 8, unit: "oz", category: "dairy" },
      { item: "tomatoes", qty: 2, unit: "", category: "produce" },
      { item: "fresh basil", qty: 1, unit: "small bunch", category: "produce" },
      { item: "balsamic glaze", qty: 2, unit: "tbsp", category: "pantry" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
      { item: "garlic", qty: 2, unit: "cloves", category: "produce" },
    ],
    steps: [
      "Season chicken and sear on the flattop until cooked through.",
      "Top each piece with tomato slices and mozzarella; cover to melt.",
      "Finish with fresh basil and a drizzle of balsamic glaze.",
    ],
  },
  {
    id: "penne-arrabbiata",
    name: "Penne Arrabbiata with Sausage",
    cuisine: "italian",
    time: 30,
    servings: 4,
    calories: 590,
    kidFriendly: false,
    blackstone: false,
    ifTip: "Cut the pasta portion and add extra sautéed veggies to the sauce.",
    ingredients: [
      { item: "penne pasta", qty: 1, unit: "lb", category: "pantry" },
      { item: "italian sausage", qty: 0.75, unit: "lb", category: "meat" },
      { item: "crushed tomatoes", qty: 1, unit: "can", category: "pantry" },
      { item: "garlic", qty: 4, unit: "cloves", category: "produce" },
      { item: "red pepper flakes", qty: 1, unit: "tsp", category: "pantry", staple: true },
      { item: "parmesan", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Boil penne until al dente.",
      "Brown sausage, then sauté garlic and red pepper flakes in the oil.",
      "Add tomatoes and simmer 10 min for a spicy sauce.",
      "Toss with pasta and parmesan.",
    ],
  },
  {
    id: "margherita-flatbread",
    name: "Blackstone Margherita Flatbreads",
    cuisine: "italian",
    time: 25,
    servings: 4,
    calories: 520,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Have one flatbread with a big side salad instead of two.",
    ingredients: [
      { item: "naan or flatbreads", qty: 4, unit: "", category: "bakery" },
      { item: "fresh mozzarella", qty: 8, unit: "oz", category: "dairy" },
      { item: "tomatoes", qty: 2, unit: "", category: "produce" },
      { item: "fresh basil", qty: 1, unit: "small bunch", category: "produce" },
      { item: "pizza sauce", qty: 0.75, unit: "cup", category: "pantry" },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Warm the flattop to medium and brush flatbreads with oil.",
      "Spread sauce, add mozzarella and tomato slices.",
      "Cover with a dome or lid until cheese melts and bottoms crisp.",
      "Top with fresh basil and cut into pieces.",
    ],
  },

  // ---------------- AMERICAN ----------------
  {
    id: "meatloaf-mashed-potatoes",
    name: "Classic Meatloaf & Mashed Potatoes",
    cuisine: "american",
    time: 60,
    servings: 5,
    calories: 640,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Skip the mashed potatoes and serve mom's slice with green beans.",
    ingredients: [
      { item: "ground beef", qty: 1.5, unit: "lb", category: "meat" },
      { item: "russet potatoes", qty: 2, unit: "lb", category: "produce" },
      { item: "breadcrumbs", qty: 0.75, unit: "cup", category: "pantry" },
      { item: "egg", qty: 1, unit: "", category: "dairy" },
      { item: "ketchup", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "milk", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "butter", qty: 3, unit: "tbsp", category: "dairy", staple: true },
    ],
    steps: [
      "Preheat oven to 375°F. Mix beef, breadcrumbs, egg, onion, and half the ketchup.",
      "Shape into a loaf, top with remaining ketchup, bake 45–50 min.",
      "Boil potatoes until tender; mash with milk and butter.",
      "Rest meatloaf 5 min, slice, and serve with mash.",
    ],
  },
  {
    id: "chicken-tenders-fries",
    name: "Homemade Chicken Tenders & Fries",
    cuisine: "american",
    time: 45,
    servings: 4,
    calories: 620,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Bake the tenders (don't fry) and swap fries for a salad or roasted veggies.",
    ingredients: [
      { item: "chicken tenders", qty: 1.5, unit: "lb", category: "meat" },
      { item: "frozen french fries", qty: 1, unit: "bag", category: "frozen" },
      { item: "panko breadcrumbs", qty: 1.5, unit: "cups", category: "pantry" },
      { item: "eggs", qty: 2, unit: "", category: "dairy" },
      { item: "flour", qty: 0.5, unit: "cup", category: "pantry", staple: true },
      { item: "paprika", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Preheat oven to 425°F and bake fries per package.",
      "Set up flour, beaten egg, and panko + paprika.",
      "Dredge tenders through each, place on a rack on a sheet pan.",
      "Bake 18–20 min, flipping once, until golden and 165°F.",
    ],
  },
  {
    id: "grilled-cheese-tomato-soup",
    name: "Grilled Cheese & Tomato Soup",
    cuisine: "american",
    time: 30,
    servings: 4,
    calories: 540,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Have a bowl of soup with just half a sandwich, or skip the butter on the bread.",
    ingredients: [
      { item: "sandwich bread", qty: 8, unit: "slices", category: "bakery" },
      { item: "cheddar cheese", qty: 8, unit: "slices", category: "dairy" },
      { item: "tomato soup", qty: 2, unit: "cans", category: "pantry" },
      { item: "butter", qty: 3, unit: "tbsp", category: "dairy", staple: true },
      { item: "milk", qty: 1, unit: "cup", category: "dairy" },
    ],
    steps: [
      "Heat tomato soup with milk until steaming.",
      "Butter bread, assemble with cheese.",
      "Griddle on the flattop until golden and melty, ~3 min per side.",
      "Cut into halves and serve with soup for dipping.",
    ],
  },
  {
    id: "pork-chops-rice",
    name: "Pan-Seared Pork Chops with Rice",
    cuisine: "american",
    time: 35,
    servings: 4,
    calories: 580,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Swap rice for roasted veggies and keep the lean chops.",
    ingredients: [
      { item: "pork chops", qty: 4, unit: "", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "green beans", qty: 1, unit: "lb", category: "produce" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "butter", qty: 2, unit: "tbsp", category: "dairy", staple: true },
      { item: "paprika", qty: 1, unit: "tsp", category: "pantry", staple: true },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Season chops with paprika, salt, and pepper; sear 4–5 min per side.",
      "Add butter and garlic, baste the chops, and rest.",
      "Sauté green beans; serve everything together.",
    ],
  },
  {
    id: "buffalo-chicken-wraps",
    name: "Buffalo Chicken Wraps",
    cuisine: "american",
    time: 30,
    servings: 4,
    calories: 560,
    kidFriendly: false,
    blackstone: true,
    ifTip: "Make it a salad bowl with extra lettuce and light dressing, skip the wrap.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "large flour tortillas", qty: 4, unit: "", category: "bakery" },
      { item: "buffalo sauce", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "romaine lettuce", qty: 1, unit: "head", category: "produce" },
      { item: "shredded cheddar", qty: 1, unit: "cup", category: "dairy" },
      { item: "ranch dressing", qty: 0.5, unit: "cup", category: "pantry" },
    ],
    steps: [
      "Dice and cook chicken on the flattop; toss with buffalo sauce.",
      "Lay out tortillas; add lettuce, chicken, cheese, and ranch.",
      "Roll up tightly and griddle seam-side down to crisp.",
      "Slice in half to serve.",
    ],
  },
  {
    id: "patty-melts",
    name: "Blackstone Patty Melts",
    cuisine: "american",
    time: 35,
    servings: 4,
    calories: 680,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Go open-faced on one slice of bread, or skip bread and eat the patty with onions.",
    ingredients: [
      { item: "ground beef (80/20)", qty: 1.25, unit: "lb", category: "meat" },
      { item: "rye bread", qty: 8, unit: "slices", category: "bakery" },
      { item: "swiss cheese", qty: 8, unit: "slices", category: "dairy" },
      { item: "yellow onion", qty: 2, unit: "", category: "produce" },
      { item: "butter", qty: 3, unit: "tbsp", category: "dairy", staple: true },
    ],
    steps: [
      "Caramelize sliced onions low and slow on the flattop.",
      "Form thin patties and sear until cooked.",
      "Butter bread; build with swiss, patty, onions, swiss.",
      "Griddle until golden and the cheese melts.",
    ],
  },
  {
    id: "philly-cheesesteaks",
    name: "Blackstone Philly Cheesesteaks",
    cuisine: "american",
    time: 30,
    servings: 4,
    calories: 660,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Skip the roll and eat the steak, peppers, and onions as a bowl.",
    ingredients: [
      { item: "thin-sliced steak (or shaved beef)", qty: 1.5, unit: "lb", category: "meat" },
      { item: "hoagie rolls", qty: 4, unit: "", category: "bakery" },
      { item: "provolone cheese", qty: 8, unit: "slices", category: "dairy" },
      { item: "green bell peppers", qty: 2, unit: "", category: "produce" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Sauté peppers and onion on the flattop until soft; push aside.",
      "Sear the beef, season, then chop and mix with the veggies.",
      "Lay provolone over the pile to melt.",
      "Scoop into toasted hoagie rolls.",
    ],
  },
  {
    id: "mac-and-cheese-ham",
    name: "Stovetop Mac & Cheese with Ham",
    cuisine: "american",
    time: 30,
    servings: 5,
    calories: 600,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Take a smaller scoop and pair with a big pile of steamed broccoli.",
    ingredients: [
      { item: "elbow macaroni", qty: 1, unit: "lb", category: "pantry" },
      { item: "diced ham", qty: 2, unit: "cups", category: "meat" },
      { item: "cheddar cheese", qty: 3, unit: "cups", category: "dairy" },
      { item: "milk", qty: 2, unit: "cups", category: "dairy" },
      { item: "butter", qty: 3, unit: "tbsp", category: "dairy", staple: true },
      { item: "flour", qty: 3, unit: "tbsp", category: "pantry", staple: true },
      { item: "broccoli", qty: 1, unit: "head", category: "produce" },
    ],
    steps: [
      "Boil macaroni; steam broccoli alongside.",
      "Melt butter, whisk in flour, then milk; cook until thick.",
      "Stir in cheese until smooth; fold in pasta and ham.",
      "Serve with the broccoli.",
    ],
  },
  {
    id: "breakfast-for-dinner",
    name: "Blackstone Breakfast for Dinner",
    cuisine: "american",
    time: 30,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Load up on eggs and skip the pancakes; have fruit on the side.",
    ingredients: [
      { item: "eggs", qty: 8, unit: "", category: "dairy" },
      { item: "bacon", qty: 8, unit: "slices", category: "meat" },
      { item: "pancake mix", qty: 2, unit: "cups", category: "pantry" },
      { item: "hash browns", qty: 1, unit: "bag", category: "frozen" },
      { item: "butter", qty: 2, unit: "tbsp", category: "dairy", staple: true },
      { item: "maple syrup", qty: 0.5, unit: "cup", category: "pantry" },
    ],
    steps: [
      "Crisp bacon on the flattop; cook hash browns in the drippings.",
      "Pour pancakes on a buttered zone and flip when bubbly.",
      "Scramble or fry the eggs.",
      "Plate it all up with syrup.",
    ],
  },
  {
    id: "chili-con-carne",
    name: "Beef Chili con Carne",
    cuisine: "american",
    time: 50,
    servings: 6,
    calories: 480,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Already hearty and lean-friendly — skip the cheese and cornbread, add extra beans.",
    ingredients: [
      { item: "ground beef", qty: 1.5, unit: "lb", category: "meat" },
      { item: "kidney beans", qty: 2, unit: "cans", category: "pantry" },
      { item: "diced tomatoes", qty: 1, unit: "can", category: "pantry" },
      { item: "tomato sauce", qty: 1, unit: "can", category: "pantry" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "bell pepper", qty: 1, unit: "", category: "produce" },
      { item: "chili powder", qty: 2, unit: "tbsp", category: "pantry", staple: true },
      { item: "shredded cheddar", qty: 1, unit: "cup", category: "dairy" },
    ],
    steps: [
      "Brown beef with onion and pepper; drain.",
      "Stir in chili powder, tomatoes, tomato sauce, and beans.",
      "Simmer 30–40 min, stirring occasionally.",
      "Serve topped with cheese.",
    ],
  },

  // ---------------- RICE BOWLS ----------------
  {
    id: "chicken-fried-rice",
    name: "Blackstone Chicken Fried Rice",
    cuisine: "ricebowl",
    time: 30,
    servings: 4,
    calories: 540,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Use cauliflower rice and go heavy on the egg and veggies.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "cooked white rice", qty: 4, unit: "cups", category: "pantry" },
      { item: "eggs", qty: 3, unit: "", category: "dairy" },
      { item: "frozen peas and carrots", qty: 2, unit: "cups", category: "frozen" },
      { item: "soy sauce", qty: 0.25, unit: "cup", category: "pantry" },
      { item: "green onions", qty: 1, unit: "bunch", category: "produce" },
      { item: "sesame oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "vegetable oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook diced chicken on the hot flattop; push aside.",
      "Scramble the eggs, then add peas and carrots.",
      "Add cold rice, soy sauce, and sesame oil; fry until sizzling.",
      "Mix everything and finish with green onions.",
    ],
  },
  {
    id: "beef-and-broccoli-bowl",
    name: "Beef & Broccoli Rice Bowl",
    cuisine: "ricebowl",
    time: 30,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Serve over cauliflower rice and use a low-sodium, low-sugar sauce.",
    ingredients: [
      { item: "flank steak", qty: 1.25, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "broccoli", qty: 1, unit: "large head", category: "produce" },
      { item: "soy sauce", qty: 0.33, unit: "cup", category: "pantry" },
      { item: "brown sugar", qty: 2, unit: "tbsp", category: "pantry", staple: true },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "cornstarch", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "ginger", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Sear thin-sliced beef in batches; set aside.",
      "Stir-fry broccoli with garlic and ginger.",
      "Add soy, brown sugar, and cornstarch slurry; return beef and toss to glaze. Serve over rice.",
    ],
  },
  {
    id: "hawaiian-chicken-bowl",
    name: "Hawaiian Pineapple Chicken Bowl",
    cuisine: "ricebowl",
    time: 30,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Skip the rice, double the veggies, and use less of the sweet sauce.",
    ingredients: [
      { item: "chicken thighs", qty: 1.5, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "pineapple chunks", qty: 1, unit: "can", category: "pantry" },
      { item: "bell pepper", qty: 1, unit: "", category: "produce" },
      { item: "teriyaki sauce", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "green onions", qty: 1, unit: "bunch", category: "produce" },
      { item: "vegetable oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Sear diced chicken on the flattop until golden.",
      "Add pepper and pineapple; char slightly.",
      "Glaze with teriyaki; serve over rice with green onions.",
    ],
  },
  {
    id: "chicken-katsu-bowl",
    name: "Chicken Katsu Bowl",
    cuisine: "ricebowl",
    time: 40,
    servings: 4,
    calories: 620,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Bake the cutlets instead of frying and serve over cauliflower rice.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "panko breadcrumbs", qty: 1.5, unit: "cups", category: "pantry" },
      { item: "eggs", qty: 2, unit: "", category: "dairy" },
      { item: "flour", qty: 0.5, unit: "cup", category: "pantry", staple: true },
      { item: "tonkatsu sauce", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "cabbage", qty: 0.25, unit: "head", category: "produce" },
    ],
    steps: [
      "Cook rice.",
      "Pound chicken thin; coat in flour, egg, then panko.",
      "Pan-fry until golden and cooked through; slice.",
      "Serve over rice with shredded cabbage and tonkatsu sauce.",
    ],
  },
  {
    id: "sweet-chili-chicken-bowl",
    name: "Sweet Chili Chicken Bowl",
    cuisine: "ricebowl",
    time: 30,
    servings: 4,
    calories: 550,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Use cauliflower rice and thin the sweet chili sauce with lime juice.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "sweet chili sauce", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "broccoli", qty: 1, unit: "head", category: "produce" },
      { item: "carrots", qty: 2, unit: "", category: "produce" },
      { item: "lime", qty: 1, unit: "", category: "produce" },
      { item: "vegetable oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Sear diced chicken on the flattop until cooked.",
      "Add broccoli and carrots; cook until crisp-tender.",
      "Toss with sweet chili sauce and lime; serve over rice.",
    ],
  },
  {
    id: "pork-bulgogi-bowl",
    name: "Pork Bulgogi Bowl",
    cuisine: "ricebowl",
    time: 30,
    servings: 4,
    calories: 580,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Cut the sugar in half and serve over cauliflower rice with extra cucumber.",
    ingredients: [
      { item: "thin-sliced pork", qty: 1.25, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "soy sauce", qty: 0.25, unit: "cup", category: "pantry" },
      { item: "brown sugar", qty: 2, unit: "tbsp", category: "pantry", staple: true },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "cucumber", qty: 1, unit: "", category: "produce" },
      { item: "green onions", qty: 1, unit: "bunch", category: "produce" },
      { item: "sesame oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Marinate pork in soy, brown sugar, garlic, and sesame oil 10 min.",
      "Sear on the hot flattop until caramelized.",
      "Serve over rice with sliced cucumber and green onions.",
    ],
  },
  {
    id: "ground-turkey-taco-bowl",
    name: "Ground Turkey Taco Rice Bowl",
    cuisine: "ricebowl",
    time: 30,
    servings: 4,
    calories: 500,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Lean turkey already — skip rice for lettuce and load on salsa.",
    ingredients: [
      { item: "ground turkey", qty: 1, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "black beans", qty: 1, unit: "can", category: "pantry" },
      { item: "corn", qty: 1, unit: "can", category: "pantry" },
      { item: "salsa", qty: 1, unit: "jar", category: "pantry" },
      { item: "shredded cheese", qty: 1, unit: "cup", category: "dairy" },
      { item: "taco seasoning", qty: 1, unit: "packet", category: "pantry" },
    ],
    steps: [
      "Cook rice.",
      "Brown turkey with taco seasoning and a splash of water.",
      "Warm beans and corn.",
      "Build bowls: rice, turkey, beans, corn, salsa, cheese.",
    ],
  },
  {
    id: "egg-roll-in-a-bowl",
    name: "Egg Roll in a Bowl",
    cuisine: "ricebowl",
    time: 25,
    servings: 4,
    calories: 420,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Naturally low-carb — skip the rice entirely and enjoy as is.",
    ingredients: [
      { item: "ground pork", qty: 1, unit: "lb", category: "meat" },
      { item: "coleslaw mix", qty: 1, unit: "bag", category: "produce" },
      { item: "white rice", qty: 1, unit: "cup (dry)", category: "pantry" },
      { item: "soy sauce", qty: 0.25, unit: "cup", category: "pantry" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "ginger", qty: 1, unit: "tsp", category: "pantry", staple: true },
      { item: "green onions", qty: 1, unit: "bunch", category: "produce" },
      { item: "sesame oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice for the kids (optional).",
      "Brown pork with garlic and ginger on the flattop.",
      "Add coleslaw mix and soy sauce; stir-fry until wilted.",
      "Finish with sesame oil and green onions.",
    ],
  },
  {
    id: "chicken-shawarma-bowl",
    name: "Chicken Shawarma Bowl",
    cuisine: "ricebowl",
    time: 35,
    servings: 4,
    calories: 560,
    kidFriendly: false,
    blackstone: true,
    ifTip: "Swap rice for a big chopped salad and use extra lemon instead of sauce.",
    ingredients: [
      { item: "chicken thighs", qty: 1.5, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "cucumber", qty: 1, unit: "", category: "produce" },
      { item: "tomatoes", qty: 2, unit: "", category: "produce" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "plain yogurt", qty: 1, unit: "cup", category: "dairy" },
      { item: "lemon", qty: 1, unit: "", category: "produce" },
      { item: "shawarma seasoning", qty: 2, unit: "tbsp", category: "pantry" },
    ],
    steps: [
      "Cook rice.",
      "Toss chicken with shawarma seasoning and sear on the flattop; slice.",
      "Mix yogurt with grated garlic and lemon for a quick sauce.",
      "Build bowls: rice, chicken, diced cucumber and tomato, yogurt sauce.",
    ],
  },
  {
    id: "honey-garlic-chicken-bowl",
    name: "Honey Garlic Chicken Bowl",
    cuisine: "ricebowl",
    time: 30,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Use cauliflower rice and cut the honey by half.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "honey", qty: 0.25, unit: "cup", category: "pantry" },
      { item: "soy sauce", qty: 3, unit: "tbsp", category: "pantry" },
      { item: "garlic", qty: 4, unit: "cloves", category: "produce" },
      { item: "broccoli", qty: 1, unit: "head", category: "produce" },
      { item: "vegetable oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Sear diced chicken on the flattop.",
      "Add garlic, honey, and soy; cook until glossy and sticky.",
      "Steam broccoli; serve everything over rice.",
    ],
  },

  // ---------------- MEDITERRANEAN / GREEK ----------------
  {
    id: "greek-chicken-bowls",
    name: "Greek Chicken Bowls",
    cuisine: "mediterranean",
    time: 35,
    servings: 4,
    calories: 540,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Swap rice for extra cucumber-tomato salad and use less tzatziki.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "cucumber", qty: 1, unit: "", category: "produce" },
      { item: "tomatoes", qty: 2, unit: "", category: "produce" },
      { item: "feta cheese", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "plain yogurt", qty: 1, unit: "cup", category: "dairy" },
      { item: "lemon", qty: 1, unit: "", category: "produce" },
      { item: "oregano", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Toss diced chicken with lemon, oregano, and oil; sear on the flattop.",
      "Stir grated cucumber and a little garlic into the yogurt for tzatziki.",
      "Build bowls: rice, chicken, diced tomato and cucumber, feta, tzatziki.",
    ],
  },
  {
    id: "chicken-gyros",
    name: "Blackstone Chicken Gyros",
    cuisine: "mediterranean",
    time: 35,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Skip the pita and pile everything over a chopped salad.",
    ingredients: [
      { item: "chicken thighs", qty: 1.5, unit: "lb", category: "meat" },
      { item: "pita bread", qty: 6, unit: "", category: "bakery" },
      { item: "red onion", qty: 1, unit: "", category: "produce" },
      { item: "tomatoes", qty: 2, unit: "", category: "produce" },
      { item: "cucumber", qty: 1, unit: "", category: "produce" },
      { item: "plain yogurt", qty: 1, unit: "cup", category: "dairy" },
      { item: "lemon", qty: 1, unit: "", category: "produce" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "oregano", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Marinate chicken in lemon, garlic, oregano, and oil; sear on the flattop and slice.",
      "Mix yogurt with grated cucumber and garlic for tzatziki.",
      "Warm pitas on the griddle.",
      "Fill with chicken, onion, tomato, and tzatziki.",
    ],
  },
  {
    id: "greek-lemon-chicken-potatoes",
    name: "Greek Lemon Chicken & Potatoes",
    cuisine: "mediterranean",
    time: 55,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Have extra chicken with a side salad and go light on the potatoes.",
    ingredients: [
      { item: "chicken thighs", qty: 2, unit: "lb", category: "meat" },
      { item: "baby potatoes", qty: 1.5, unit: "lb", category: "produce" },
      { item: "lemon", qty: 2, unit: "", category: "produce" },
      { item: "garlic", qty: 4, unit: "cloves", category: "produce" },
      { item: "chicken broth", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "oregano", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "olive oil", qty: 3, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Preheat oven to 425°F.",
      "Toss chicken and halved potatoes with lemon juice, garlic, oregano, oil, and broth.",
      "Roast 40–45 min, turning once, until chicken hits 175°F and potatoes are tender.",
    ],
  },
  {
    id: "mediterranean-chicken-pasta",
    name: "Mediterranean Chicken Pasta",
    cuisine: "mediterranean",
    time: 35,
    servings: 4,
    calories: 580,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Cut the pasta in half and bulk it up with extra spinach and tomatoes.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "penne pasta", qty: 12, unit: "oz", category: "pantry" },
      { item: "cherry tomatoes", qty: 1, unit: "cup", category: "produce" },
      { item: "spinach", qty: 3, unit: "cups", category: "produce" },
      { item: "feta cheese", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "kalamata olives", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Boil penne; reserve a splash of pasta water.",
      "Sear diced chicken in oil with garlic.",
      "Add tomatoes and olives; cook until tomatoes burst.",
      "Toss with pasta and spinach until wilted; finish with feta.",
    ],
  },
  {
    id: "beef-kofta",
    name: "Blackstone Beef Kofta",
    cuisine: "mediterranean",
    time: 30,
    servings: 4,
    calories: 520,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Serve over salad instead of rice or pita with extra tzatziki.",
    ingredients: [
      { item: "ground beef", qty: 1.5, unit: "lb", category: "meat" },
      { item: "pita bread", qty: 4, unit: "", category: "bakery" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "plain yogurt", qty: 1, unit: "cup", category: "dairy" },
      { item: "cucumber", qty: 1, unit: "", category: "produce" },
      { item: "cumin", qty: 1, unit: "tsp", category: "pantry", staple: true },
      { item: "parsley", qty: 1, unit: "small bunch", category: "produce" },
    ],
    steps: [
      "Mix beef with grated onion, garlic, cumin, parsley, and salt.",
      "Form into logs and sear on the flattop until browned all over.",
      "Mix yogurt with grated cucumber for a quick sauce.",
      "Serve with warm pita and sauce.",
    ],
  },
  {
    id: "greek-pita-pizzas",
    name: "Greek Pita Pizzas",
    cuisine: "mediterranean",
    time: 25,
    servings: 4,
    calories: 500,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Have one pita with a big Greek salad on the side.",
    ingredients: [
      { item: "pita bread", qty: 4, unit: "", category: "bakery" },
      { item: "chicken breast", qty: 0.75, unit: "lb", category: "meat" },
      { item: "pizza sauce", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "mozzarella", qty: 1.5, unit: "cups", category: "dairy" },
      { item: "feta cheese", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "tomatoes", qty: 1, unit: "", category: "produce" },
      { item: "red onion", qty: 0.5, unit: "", category: "produce" },
    ],
    steps: [
      "Cook and dice chicken.",
      "Spread sauce on pitas; top with mozzarella, chicken, tomato, onion, and feta.",
      "Griddle on the flattop under a dome (or bake at 425°F) until cheese melts and edges crisp.",
    ],
  },
  {
    id: "lemon-herb-pork-chops",
    name: "Lemon-Herb Pork Chops",
    cuisine: "mediterranean",
    time: 35,
    servings: 4,
    calories: 540,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Skip the orzo and double the roasted vegetables.",
    ingredients: [
      { item: "pork chops", qty: 4, unit: "", category: "meat" },
      { item: "orzo pasta", qty: 1.5, unit: "cups", category: "pantry" },
      { item: "zucchini", qty: 2, unit: "", category: "produce" },
      { item: "lemon", qty: 1, unit: "", category: "produce" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "oregano", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook orzo.",
      "Season chops with lemon, garlic, and oregano; sear on the flattop 4–5 min per side.",
      "Griddle sliced zucchini until tender.",
      "Serve chops over orzo with the zucchini.",
    ],
  },
  {
    id: "chickpea-tomato-stew",
    name: "Chickpea & Tomato Stew",
    cuisine: "mediterranean",
    time: 35,
    servings: 5,
    calories: 380,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Naturally light and cheap — skip the bread and add extra spinach.",
    ingredients: [
      { item: "chickpeas", qty: 2, unit: "cans", category: "pantry" },
      { item: "crushed tomatoes", qty: 1, unit: "can", category: "pantry" },
      { item: "spinach", qty: 4, unit: "cups", category: "produce" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "pita bread", qty: 4, unit: "", category: "bakery" },
      { item: "cumin", qty: 1, unit: "tsp", category: "pantry", staple: true },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Sauté onion and garlic in oil until soft.",
      "Add cumin, chickpeas, and tomatoes; simmer 15 min.",
      "Stir in spinach until wilted.",
      "Serve with warm pita for dipping.",
    ],
  },
  {
    id: "greek-turkey-meatballs",
    name: "Greek Turkey Meatballs",
    cuisine: "mediterranean",
    time: 40,
    servings: 4,
    calories: 500,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Lean turkey already — serve over salad instead of rice with extra tzatziki.",
    ingredients: [
      { item: "ground turkey", qty: 1.25, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "breadcrumbs", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "egg", qty: 1, unit: "", category: "dairy" },
      { item: "plain yogurt", qty: 1, unit: "cup", category: "dairy" },
      { item: "cucumber", qty: 1, unit: "", category: "produce" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "oregano", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Preheat oven to 400°F. Cook rice.",
      "Mix turkey, breadcrumbs, egg, garlic, and oregano; roll into meatballs.",
      "Bake 18–20 min until cooked through.",
      "Mix yogurt with grated cucumber; serve meatballs over rice with the sauce.",
    ],
  },
  {
    id: "baked-feta-chicken-pasta",
    name: "Baked Feta Chicken Pasta",
    cuisine: "mediterranean",
    time: 45,
    servings: 5,
    calories: 600,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Use less pasta and more cherry tomatoes and chicken.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "penne pasta", qty: 12, unit: "oz", category: "pantry" },
      { item: "block feta cheese", qty: 8, unit: "oz", category: "dairy" },
      { item: "cherry tomatoes", qty: 2, unit: "cups", category: "produce" },
      { item: "garlic", qty: 4, unit: "cloves", category: "produce" },
      { item: "spinach", qty: 2, unit: "cups", category: "produce" },
      { item: "olive oil", qty: 3, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Preheat oven to 400°F. Place feta block in a dish surrounded by tomatoes, garlic, and oil.",
      "Bake 25–30 min until tomatoes burst and feta softens.",
      "Meanwhile, boil penne and sear diced chicken.",
      "Smash the feta and tomatoes into a sauce; toss with pasta, chicken, and spinach.",
    ],
  },

  // ---------------- ASIAN STIR-FRY & NOODLES ----------------
  {
    id: "chicken-lo-mein",
    name: "Blackstone Chicken Lo Mein",
    cuisine: "asian",
    time: 30,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Use half noodles, half extra veggies and a low-sodium sauce.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "lo mein or spaghetti noodles", qty: 12, unit: "oz", category: "pantry" },
      { item: "coleslaw mix", qty: 1, unit: "bag", category: "produce" },
      { item: "bell pepper", qty: 1, unit: "", category: "produce" },
      { item: "soy sauce", qty: 0.33, unit: "cup", category: "pantry" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "sesame oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "brown sugar", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Boil noodles.",
      "Sear diced chicken on the flattop with garlic.",
      "Add coleslaw mix and pepper; stir-fry until crisp-tender.",
      "Toss in noodles, soy sauce, sesame oil, and brown sugar.",
    ],
  },
  {
    id: "beef-chow-mein",
    name: "Beef Chow Mein",
    cuisine: "asian",
    time: 30,
    servings: 4,
    calories: 580,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Bulk up with extra cabbage and use less noodle.",
    ingredients: [
      { item: "flank steak", qty: 1.25, unit: "lb", category: "meat" },
      { item: "chow mein or spaghetti noodles", qty: 12, unit: "oz", category: "pantry" },
      { item: "cabbage", qty: 0.5, unit: "head", category: "produce" },
      { item: "carrots", qty: 2, unit: "", category: "produce" },
      { item: "soy sauce", qty: 0.33, unit: "cup", category: "pantry" },
      { item: "oyster sauce", qty: 2, unit: "tbsp", category: "pantry" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "vegetable oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Boil noodles.",
      "Sear thin-sliced beef on the hot flattop; set aside.",
      "Stir-fry cabbage, carrots, and garlic until crisp-tender.",
      "Add noodles, beef, soy, and oyster sauce; toss to combine.",
    ],
  },
  {
    id: "sesame-chicken-noodles",
    name: "Sesame Chicken Noodles",
    cuisine: "asian",
    time: 25,
    servings: 4,
    calories: 540,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Serve cold over extra cucumber and shredded carrot; halve the noodles.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "spaghetti noodles", qty: 12, unit: "oz", category: "pantry" },
      { item: "soy sauce", qty: 0.25, unit: "cup", category: "pantry" },
      { item: "peanut butter", qty: 2, unit: "tbsp", category: "pantry" },
      { item: "honey", qty: 2, unit: "tbsp", category: "pantry" },
      { item: "green onions", qty: 1, unit: "bunch", category: "produce" },
      { item: "sesame oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "garlic", qty: 2, unit: "cloves", category: "produce" },
    ],
    steps: [
      "Boil noodles.",
      "Cook diced chicken until done.",
      "Whisk soy, peanut butter, honey, sesame oil, and garlic into a sauce.",
      "Toss noodles and chicken in the sauce; top with green onions.",
    ],
  },
  {
    id: "sweet-sour-chicken",
    name: "Sweet & Sour Chicken",
    cuisine: "asian",
    time: 35,
    servings: 4,
    calories: 580,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Skip the rice and cut the sugar in the sauce by half.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "pineapple chunks", qty: 1, unit: "can", category: "pantry" },
      { item: "bell peppers", qty: 2, unit: "", category: "produce" },
      { item: "ketchup", qty: 0.25, unit: "cup", category: "pantry" },
      { item: "rice vinegar", qty: 3, unit: "tbsp", category: "pantry" },
      { item: "brown sugar", qty: 3, unit: "tbsp", category: "pantry", staple: true },
      { item: "cornstarch", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Brown diced chicken in a skillet.",
      "Add peppers and pineapple; cook 3 min.",
      "Stir in ketchup, vinegar, sugar, and cornstarch slurry until glossy. Serve over rice.",
    ],
  },
  {
    id: "pork-veggie-stir-fry",
    name: "Pork & Veggie Stir-Fry",
    cuisine: "asian",
    time: 30,
    servings: 4,
    calories: 520,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Serve over cauliflower rice and pile on extra vegetables.",
    ingredients: [
      { item: "pork tenderloin", qty: 1.25, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "broccoli", qty: 1, unit: "head", category: "produce" },
      { item: "snap peas", qty: 2, unit: "cups", category: "produce" },
      { item: "carrots", qty: 2, unit: "", category: "produce" },
      { item: "soy sauce", qty: 0.25, unit: "cup", category: "pantry" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "ginger", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Sear sliced pork on the flattop; set aside.",
      "Stir-fry broccoli, snap peas, and carrots with garlic and ginger.",
      "Return pork, add soy sauce, and toss. Serve over rice.",
    ],
  },
  {
    id: "orange-chicken-stir-fry",
    name: "Orange Chicken Stir-Fry",
    cuisine: "asian",
    time: 35,
    servings: 4,
    calories: 590,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Halve the sauce sugar and serve over steamed broccoli instead of rice.",
    ingredients: [
      { item: "chicken thighs", qty: 1.5, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "orange", qty: 2, unit: "", category: "produce" },
      { item: "soy sauce", qty: 3, unit: "tbsp", category: "pantry" },
      { item: "brown sugar", qty: 3, unit: "tbsp", category: "pantry", staple: true },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "cornstarch", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "broccoli", qty: 1, unit: "head", category: "produce" },
    ],
    steps: [
      "Cook rice.",
      "Brown diced chicken until crisp.",
      "Add orange juice and zest, soy, sugar, garlic, and cornstarch slurry; simmer to glaze.",
      "Steam broccoli; serve everything over rice.",
    ],
  },
  {
    id: "garlic-butter-noodles-chicken",
    name: "Garlic Butter Noodles with Chicken",
    cuisine: "asian",
    time: 25,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Use less noodle and add a big handful of stir-fried greens.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "spaghetti noodles", qty: 12, unit: "oz", category: "pantry" },
      { item: "soy sauce", qty: 3, unit: "tbsp", category: "pantry" },
      { item: "butter", qty: 3, unit: "tbsp", category: "dairy", staple: true },
      { item: "garlic", qty: 4, unit: "cloves", category: "produce" },
      { item: "green onions", qty: 1, unit: "bunch", category: "produce" },
      { item: "brown sugar", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Boil noodles.",
      "Sear diced chicken on the flattop.",
      "Add butter and garlic, then soy and brown sugar.",
      "Toss in noodles and green onions until coated.",
    ],
  },
  {
    id: "teriyaki-veggie-noodle-stirfry",
    name: "Teriyaki Veggie Noodle Stir-Fry",
    cuisine: "asian",
    time: 25,
    servings: 4,
    calories: 480,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Add extra veggies and a fried egg for protein; cut the noodles.",
    ingredients: [
      { item: "chicken breast", qty: 1, unit: "lb", category: "meat" },
      { item: "spaghetti or udon noodles", qty: 12, unit: "oz", category: "pantry" },
      { item: "frozen stir-fry vegetables", qty: 4, unit: "cups", category: "frozen" },
      { item: "teriyaki sauce", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "sesame oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Boil noodles.",
      "Sear diced chicken on the flattop with garlic.",
      "Add frozen vegetables and cook until hot and crisp-tender.",
      "Toss with noodles, teriyaki, and sesame oil.",
    ],
  },
  {
    id: "ground-beef-ramen-stirfry",
    name: "Ground Beef Ramen Stir-Fry",
    cuisine: "asian",
    time: 25,
    servings: 4,
    calories: 540,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Skip one noodle cake and double the coleslaw veggies.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "instant ramen", qty: 3, unit: "packs", category: "pantry" },
      { item: "coleslaw mix", qty: 1, unit: "bag", category: "produce" },
      { item: "soy sauce", qty: 0.25, unit: "cup", category: "pantry" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "brown sugar", qty: 2, unit: "tbsp", category: "pantry", staple: true },
      { item: "green onions", qty: 1, unit: "bunch", category: "produce" },
    ],
    steps: [
      "Boil ramen noodles (discard the seasoning packets); drain.",
      "Brown beef with garlic on the flattop.",
      "Add coleslaw mix and cook until wilted.",
      "Toss in noodles, soy sauce, and brown sugar; top with green onions.",
    ],
  },
  {
    id: "honey-soy-chicken-stir-fry",
    name: "Honey Soy Chicken Stir-Fry",
    cuisine: "asian",
    time: 30,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Cut the honey in half and serve over cauliflower rice.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "bell peppers", qty: 2, unit: "", category: "produce" },
      { item: "snap peas", qty: 2, unit: "cups", category: "produce" },
      { item: "honey", qty: 3, unit: "tbsp", category: "pantry" },
      { item: "soy sauce", qty: 3, unit: "tbsp", category: "pantry" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "vegetable oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Sear diced chicken on the flattop.",
      "Add peppers and snap peas; stir-fry until crisp-tender.",
      "Add honey, soy, and garlic; toss to glaze. Serve over rice.",
    ],
  },
];
