/*
 * Recipe database for the Family Dinner Planner.
 *
 * Rules baked into the data:
 *   - No seafood (none included).
 *   - No berries (none included).
 *   - Cuisines: mexican, italian, american, ricebowl, casserole.
 *   - kidFriendly: meals a 2-year-old (Wesley) will happily eat, no separate cooking.
 *   - blackstone: works great on a flattop / Blackstone griddle.
 *   - ifTip: an easy way to cut calories for mom's intermittent fasting.
 *
 * Ingredient categories drive the grocery-list grouping:
 *   produce, meat, dairy, pantry, bakery, frozen.
 * staple:true marks common things you likely already have (oil, salt, etc.) —
 * they still show up so you can verify, but are grouped under "Pantry staples".
 */

const CUISINE_LABELS = {
  mexican: "Mexican",
  italian: "Italian",
  american: "American",
  ricebowl: "Rice Bowls",
  casserole: "Casseroles",
};

const CATEGORY_ORDER = ["produce", "meat", "dairy", "frozen", "bakery", "pantry"];
const CATEGORY_LABELS = {
  produce: "Produce",
  meat: "Meat & Protein",
  dairy: "Dairy & Eggs",
  frozen: "Frozen",
  bakery: "Bakery",
  pantry: "Pantry staples",
};

const RECIPES = [
  // ---------------- MEXICAN ----------------
  {
    id: "beef-burrito-bowls",
    name: "Beef Burrito Bowls",
    cuisine: "mexican",
    time: 35,
    servings: 4,
    calories: 620,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Skip the rice and double the lettuce/pico for a burrito salad — saves ~200 cal.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "black beans", qty: 1, unit: "can", category: "pantry" },
      { item: "shredded cheddar", qty: 1, unit: "cup", category: "dairy" },
      { item: "romaine lettuce", qty: 1, unit: "head", category: "produce" },
      { item: "roma tomatoes", qty: 2, unit: "", category: "produce" },
      { item: "lime", qty: 1, unit: "", category: "produce" },
      { item: "taco seasoning", qty: 1, unit: "packet", category: "pantry" },
      { item: "sour cream", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "salt", qty: 1, unit: "pinch", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice per package directions; fluff and stir in a squeeze of lime and a pinch of salt.",
      "Brown the ground beef over medium-high, drain, then stir in taco seasoning + a splash of water. Simmer 3–4 min.",
      "Warm the black beans in a small pot.",
      "Dice tomatoes and chop romaine.",
      "Build bowls: rice, beef, beans, cheese, lettuce, tomato, and a dollop of sour cream.",
    ],
  },
  {
    id: "chicken-fajitas",
    name: "Blackstone Chicken Fajitas",
    cuisine: "mexican",
    time: 30,
    servings: 4,
    calories: 540,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Serve over shredded lettuce instead of tortillas; mom keeps the chicken + peppers.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "bell peppers", qty: 3, unit: "", category: "produce" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "flour tortillas", qty: 8, unit: "", category: "bakery" },
      { item: "shredded cheese", qty: 1, unit: "cup", category: "dairy" },
      { item: "fajita seasoning", qty: 2, unit: "tbsp", category: "pantry" },
      { item: "lime", qty: 1, unit: "", category: "produce" },
      { item: "sour cream", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Slice chicken, peppers, and onion into thin strips.",
      "Heat the Blackstone (or large skillet) to high with oil.",
      "Cook chicken with fajita seasoning until browned, ~6 min; push to a cooler zone.",
      "Sear peppers and onion until charred-tender, ~5 min. Squeeze lime over everything.",
      "Warm tortillas on the griddle. Serve with cheese and sour cream.",
    ],
  },
  {
    id: "beef-enchilada-bake",
    name: "Beef Enchilada Bake",
    cuisine: "mexican",
    time: 50,
    servings: 6,
    calories: 580,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Have one portion with extra salsa instead of cheese on top to trim ~150 cal.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "corn tortillas", qty: 12, unit: "", category: "bakery" },
      { item: "red enchilada sauce", qty: 2, unit: "cans", category: "pantry" },
      { item: "black beans", qty: 1, unit: "can", category: "pantry" },
      { item: "shredded Mexican cheese", qty: 2, unit: "cups", category: "dairy" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "cumin", qty: 1, unit: "tsp", category: "pantry", staple: true },
      { item: "salt", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Preheat oven to 375°F.",
      "Brown beef with diced onion and cumin; drain. Stir in beans and half the enchilada sauce.",
      "Layer in a baking dish: sauce, tortillas, beef mix, cheese. Repeat, ending with cheese.",
      "Cover with foil, bake 25 min; uncover and bake 10 more until bubbly.",
      "Rest 5 min before cutting.",
    ],
  },

  // ---------------- ITALIAN ----------------
  {
    id: "spaghetti-meat-sauce",
    name: "Spaghetti with Meat Sauce",
    cuisine: "italian",
    time: 40,
    servings: 5,
    calories: 600,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Swap half the pasta for zucchini noodles, or skip noodles and eat the sauce over sautéed zucchini.",
    ingredients: [
      { item: "spaghetti", qty: 1, unit: "lb", category: "pantry" },
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "marinara sauce", qty: 1, unit: "jar", category: "pantry" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "parmesan", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "italian seasoning", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Boil spaghetti until al dente; reserve a splash of pasta water.",
      "Sauté diced onion and garlic in oil until soft.",
      "Add beef, brown and drain. Stir in marinara + Italian seasoning; simmer 10 min.",
      "Toss pasta with sauce, loosening with pasta water if needed.",
      "Top with parmesan.",
    ],
  },
  {
    id: "chicken-parm-casserole",
    name: "Chicken Parmesan Casserole",
    cuisine: "italian",
    time: 55,
    servings: 6,
    calories: 640,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Serve mom's portion over a bed of steamed broccoli instead of pasta.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "penne pasta", qty: 12, unit: "oz", category: "pantry" },
      { item: "marinara sauce", qty: 1, unit: "jar", category: "pantry" },
      { item: "mozzarella", qty: 2, unit: "cups", category: "dairy" },
      { item: "parmesan", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "panko breadcrumbs", qty: 1, unit: "cup", category: "pantry" },
      { item: "eggs", qty: 2, unit: "", category: "dairy" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Preheat oven to 400°F and boil penne until just shy of done.",
      "Cut chicken into bite-size pieces, dip in beaten egg then panko, and pan-fry in oil until golden.",
      "Mix pasta with marinara in a baking dish; fold in the chicken.",
      "Top with mozzarella and parmesan.",
      "Bake 18–20 min until cheese is melted and golden.",
    ],
  },
  {
    id: "sausage-pepper-pasta",
    name: "Sausage & Pepper Pasta",
    cuisine: "italian",
    time: 35,
    servings: 5,
    calories: 590,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Use chicken sausage and serve over a smaller scoop of pasta with extra peppers.",
    ingredients: [
      { item: "italian sausage", qty: 1, unit: "lb", category: "meat" },
      { item: "rigatoni", qty: 1, unit: "lb", category: "pantry" },
      { item: "bell peppers", qty: 2, unit: "", category: "produce" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "marinara sauce", qty: 1, unit: "jar", category: "pantry" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "parmesan", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Boil rigatoni until al dente.",
      "On the flattop or skillet, brown sliced sausage; add peppers, onion, and garlic and cook until soft.",
      "Stir in marinara and simmer 5 min.",
      "Toss with pasta and finish with parmesan.",
    ],
  },

  // ---------------- AMERICAN ----------------
  {
    id: "smash-burgers",
    name: "Blackstone Smash Burgers",
    cuisine: "american",
    time: 30,
    servings: 4,
    calories: 680,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Go bunless (lettuce wrap) and skip the cheese to cut ~250 cal.",
    ingredients: [
      { item: "ground beef (80/20)", qty: 1.5, unit: "lb", category: "meat" },
      { item: "hamburger buns", qty: 4, unit: "", category: "bakery" },
      { item: "american cheese", qty: 4, unit: "slices", category: "dairy" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "lettuce", qty: 4, unit: "leaves", category: "produce" },
      { item: "tomato", qty: 1, unit: "", category: "produce" },
      { item: "pickles", qty: 1, unit: "jar", category: "pantry" },
      { item: "salt", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Form beef into loose 4 oz balls.",
      "Get the Blackstone screaming hot. Smash each ball flat with a spatula and salt.",
      "Cook 2–3 min until edges crisp, flip, add cheese, cook 1 more min.",
      "Toast buns on the griddle.",
      "Build with onion, lettuce, tomato, and pickles.",
    ],
  },
  {
    id: "bbq-chicken-sheetpan",
    name: "BBQ Chicken & Veggie Sheet Pan",
    cuisine: "american",
    time: 45,
    servings: 4,
    calories: 520,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Use half the BBQ sauce (sugar) and load up on the roasted veggies.",
    ingredients: [
      { item: "chicken thighs", qty: 2, unit: "lb", category: "meat" },
      { item: "baby potatoes", qty: 1.5, unit: "lb", category: "produce" },
      { item: "broccoli", qty: 1, unit: "head", category: "produce" },
      { item: "bbq sauce", qty: 0.75, unit: "cup", category: "pantry" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "pantry", staple: true },
      { item: "salt", qty: 1, unit: "tsp", category: "pantry", staple: true },
      { item: "pepper", qty: 0.5, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Preheat oven to 425°F.",
      "Halve potatoes, toss with oil, salt, pepper; roast 15 min.",
      "Add chicken (brushed with BBQ sauce) and broccoli to the pan.",
      "Roast 20–25 min until chicken hits 165°F, brushing more sauce halfway.",
    ],
  },
  {
    id: "loaded-baked-potato-bar",
    name: "Loaded Baked Potato Bar",
    cuisine: "american",
    time: 60,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Top with extra steamed broccoli + a little cheese; go light on butter and sour cream.",
    ingredients: [
      { item: "russet potatoes", qty: 4, unit: "", category: "produce" },
      { item: "bacon", qty: 6, unit: "slices", category: "meat" },
      { item: "shredded cheddar", qty: 1, unit: "cup", category: "dairy" },
      { item: "sour cream", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "green onions", qty: 1, unit: "bunch", category: "produce" },
      { item: "broccoli", qty: 1, unit: "head", category: "produce" },
      { item: "butter", qty: 2, unit: "tbsp", category: "dairy", staple: true },
    ],
    steps: [
      "Preheat oven to 400°F. Pierce potatoes, rub with oil/salt, bake 50–60 min.",
      "Cook bacon until crisp; crumble.",
      "Steam broccoli until tender.",
      "Split potatoes and set out all toppings so everyone builds their own.",
    ],
  },

  // ---------------- RICE BOWLS ----------------
  {
    id: "teriyaki-chicken-bowl",
    name: "Teriyaki Chicken Rice Bowl",
    cuisine: "ricebowl",
    time: 35,
    servings: 4,
    calories: 560,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Use cauliflower rice for mom and a low-sugar teriyaki — cuts ~200 cal.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "teriyaki sauce", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "broccoli", qty: 1, unit: "head", category: "produce" },
      { item: "carrots", qty: 2, unit: "", category: "produce" },
      { item: "sesame seeds", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "vegetable oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Dice chicken and sear on the flattop/skillet in oil until cooked through.",
      "Add teriyaki sauce and let it glaze the chicken, ~2 min.",
      "Steam or griddle the broccoli and carrots.",
      "Build bowls: rice, chicken, veggies, sprinkle of sesame seeds.",
    ],
  },
  {
    id: "korean-beef-bowl",
    name: "Korean Beef Bowl",
    cuisine: "ricebowl",
    time: 25,
    servings: 4,
    calories: 590,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Lower the brown sugar by half and serve over cauliflower rice.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "soy sauce", qty: 0.25, unit: "cup", category: "pantry" },
      { item: "brown sugar", qty: 3, unit: "tbsp", category: "pantry", staple: true },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "green onions", qty: 1, unit: "bunch", category: "produce" },
      { item: "sesame oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "ginger", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Brown beef with garlic and ginger; drain.",
      "Stir in soy sauce, brown sugar, and sesame oil; simmer 3 min.",
      "Serve over rice, topped with sliced green onions.",
    ],
  },
  {
    id: "carnitas-rice-bowl",
    name: "Carnitas Rice Bowl",
    cuisine: "ricebowl",
    time: 40,
    servings: 4,
    calories: 610,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Skip the rice, double the cabbage slaw, and add extra lime + cilantro.",
    ingredients: [
      { item: "pork shoulder (or pre-cooked carnitas)", qty: 1.5, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "black beans", qty: 1, unit: "can", category: "pantry" },
      { item: "cabbage", qty: 0.5, unit: "head", category: "produce" },
      { item: "lime", qty: 2, unit: "", category: "produce" },
      { item: "cilantro", qty: 1, unit: "bunch", category: "produce" },
      { item: "cotija cheese", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "cumin", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice; stir in lime juice and chopped cilantro.",
      "Crisp the carnitas on the flattop until edges are golden.",
      "Warm black beans with a pinch of cumin.",
      "Shred cabbage and toss with lime juice for a quick slaw.",
      "Build bowls: rice, carnitas, beans, slaw, cotija.",
    ],
  },

  // ---------------- CASSEROLES ----------------
  {
    id: "king-ranch-casserole",
    name: "King Ranch Chicken Casserole",
    cuisine: "casserole",
    time: 55,
    servings: 6,
    calories: 600,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Pair a smaller square with a big side salad instead of seconds.",
    ingredients: [
      { item: "chicken breast", qty: 1.5, unit: "lb", category: "meat" },
      { item: "corn tortillas", qty: 10, unit: "", category: "bakery" },
      { item: "cream of chicken soup", qty: 1, unit: "can", category: "pantry" },
      { item: "diced tomatoes with green chiles", qty: 1, unit: "can", category: "pantry" },
      { item: "shredded cheese", qty: 2, unit: "cups", category: "dairy" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "bell pepper", qty: 1, unit: "", category: "produce" },
      { item: "chili powder", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Preheat oven to 350°F. Cook and shred chicken.",
      "Sauté onion and pepper; stir in soup, tomatoes, and chili powder.",
      "Layer torn tortillas, chicken, sauce, and cheese in a baking dish; repeat.",
      "Bake 30–35 min until bubbly.",
    ],
  },
  {
    id: "tater-tot-casserole",
    name: "Tater Tot Casserole",
    cuisine: "casserole",
    time: 60,
    servings: 6,
    calories: 620,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Add a layer of green beans under the tots and take a smaller serving.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "tater tots", qty: 1, unit: "bag", category: "frozen" },
      { item: "cream of mushroom soup", qty: 1, unit: "can", category: "pantry" },
      { item: "frozen mixed vegetables", qty: 2, unit: "cups", category: "frozen" },
      { item: "shredded cheddar", qty: 1.5, unit: "cups", category: "dairy" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "milk", qty: 0.5, unit: "cup", category: "dairy" },
    ],
    steps: [
      "Preheat oven to 375°F.",
      "Brown beef with diced onion; drain.",
      "Mix soup with milk; stir into beef with the vegetables. Spread in a baking dish.",
      "Top with cheese, then a single layer of tater tots.",
      "Bake 35–40 min until tots are golden and crisp.",
    ],
  },
  {
    id: "baked-ziti",
    name: "Baked Ziti",
    cuisine: "casserole",
    time: 55,
    servings: 6,
    calories: 630,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Use part-skim ricotta and serve with a big green salad to fill up on fewer noodles.",
    ingredients: [
      { item: "ziti pasta", qty: 1, unit: "lb", category: "pantry" },
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "marinara sauce", qty: 2, unit: "jars", category: "pantry" },
      { item: "ricotta", qty: 15, unit: "oz", category: "dairy" },
      { item: "mozzarella", qty: 2, unit: "cups", category: "dairy" },
      { item: "parmesan", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "italian seasoning", qty: 1, unit: "tsp", category: "pantry", staple: true },
    ],
    steps: [
      "Preheat oven to 375°F and boil ziti until just under al dente.",
      "Brown beef with garlic; stir in marinara and Italian seasoning.",
      "Mix pasta with sauce and ricotta. Spread half in a dish, layer mozzarella, then the rest.",
      "Top with mozzarella and parmesan.",
      "Bake 25–30 min until golden and bubbly.",
    ],
  },

  // ---------------- A FEW MORE FOR VARIETY ----------------
  {
    id: "chicken-quesadillas",
    name: "Blackstone Chicken Quesadillas",
    cuisine: "mexican",
    time: 25,
    servings: 4,
    calories: 550,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Make mom's as a single open-faced tortilla with extra chicken, less cheese.",
    ingredients: [
      { item: "chicken breast", qty: 1, unit: "lb", category: "meat" },
      { item: "flour tortillas", qty: 8, unit: "", category: "bakery" },
      { item: "shredded Mexican cheese", qty: 2, unit: "cups", category: "dairy" },
      { item: "bell pepper", qty: 1, unit: "", category: "produce" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "taco seasoning", qty: 1, unit: "tbsp", category: "pantry" },
      { item: "salsa", qty: 1, unit: "jar", category: "pantry" },
    ],
    steps: [
      "Dice and cook chicken with taco seasoning on the flattop.",
      "Sauté peppers and onion alongside.",
      "Build quesadillas: tortilla, cheese, chicken/veg, cheese, tortilla.",
      "Griddle until golden and crispy on both sides. Cut into wedges, serve with salsa.",
    ],
  },
  {
    id: "philly-cheesesteak-bowl",
    name: "Philly Cheesesteak Rice Bowl",
    cuisine: "ricebowl",
    time: 30,
    servings: 4,
    calories: 600,
    kidFriendly: true,
    blackstone: true,
    ifTip: "Swap rice for cauliflower rice and use provolone sparingly.",
    ingredients: [
      { item: "thin-sliced steak (or shaved beef)", qty: 1.25, unit: "lb", category: "meat" },
      { item: "white rice", qty: 1.5, unit: "cups (dry)", category: "pantry" },
      { item: "bell peppers", qty: 2, unit: "", category: "produce" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "provolone cheese", qty: 4, unit: "slices", category: "dairy" },
      { item: "worcestershire sauce", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Cook rice.",
      "Sear the beef on a hot flattop; season with salt and Worcestershire.",
      "Add peppers and onion; cook until soft and a little charred.",
      "Lay provolone over the meat to melt, then chop it all together.",
      "Serve over rice.",
    ],
  },
  {
    id: "chicken-alfredo",
    name: "Chicken Alfredo",
    cuisine: "italian",
    time: 35,
    servings: 4,
    calories: 720,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Serve mom's sauce over steamed broccoli or a small portion of pasta with extra chicken.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "fettuccine", qty: 12, unit: "oz", category: "pantry" },
      { item: "heavy cream", qty: 1, unit: "cup", category: "dairy" },
      { item: "parmesan", qty: 1, unit: "cup", category: "dairy" },
      { item: "butter", qty: 3, unit: "tbsp", category: "dairy", staple: true },
      { item: "garlic", qty: 3, unit: "cloves", category: "produce" },
      { item: "broccoli", qty: 1, unit: "head", category: "produce" },
    ],
    steps: [
      "Boil fettuccine; add broccoli in the last 3 min.",
      "Season and pan-sear sliced chicken until cooked; set aside.",
      "Melt butter, sauté garlic, add cream and parmesan; simmer until thick.",
      "Toss pasta and broccoli in sauce, top with chicken.",
    ],
  },
  {
    id: "sloppy-joes",
    name: "Sloppy Joes",
    cuisine: "american",
    time: 30,
    servings: 5,
    calories: 540,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Serve the meat over a baked potato or greens instead of a bun.",
    ingredients: [
      { item: "ground beef", qty: 1.25, unit: "lb", category: "meat" },
      { item: "hamburger buns", qty: 5, unit: "", category: "bakery" },
      { item: "ketchup", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "tomato sauce", qty: 1, unit: "can", category: "pantry" },
      { item: "yellow onion", qty: 1, unit: "", category: "produce" },
      { item: "bell pepper", qty: 1, unit: "", category: "produce" },
      { item: "brown sugar", qty: 1, unit: "tbsp", category: "pantry", staple: true },
      { item: "worcestershire sauce", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Brown beef with diced onion and pepper; drain.",
      "Stir in ketchup, tomato sauce, brown sugar, and Worcestershire.",
      "Simmer 10 min until thick.",
      "Spoon onto toasted buns.",
    ],
  },
  {
    id: "taco-tuesday",
    name: "Classic Beef Tacos",
    cuisine: "mexican",
    time: 25,
    servings: 4,
    calories: 520,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Use lettuce cups instead of shells and skip the cheese.",
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "meat" },
      { item: "taco shells", qty: 12, unit: "", category: "bakery" },
      { item: "taco seasoning", qty: 1, unit: "packet", category: "pantry" },
      { item: "shredded cheddar", qty: 1, unit: "cup", category: "dairy" },
      { item: "lettuce", qty: 0.5, unit: "head", category: "produce" },
      { item: "roma tomatoes", qty: 2, unit: "", category: "produce" },
      { item: "sour cream", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "salsa", qty: 1, unit: "jar", category: "pantry" },
    ],
    steps: [
      "Brown beef, drain, add taco seasoning + water; simmer 4 min.",
      "Warm taco shells in the oven.",
      "Chop lettuce and tomatoes.",
      "Set out a taco bar and let everyone build their own.",
    ],
  },
  {
    id: "pesto-chicken-pasta",
    name: "Pesto Chicken Pasta",
    cuisine: "italian",
    time: 30,
    servings: 4,
    calories: 610,
    kidFriendly: true,
    blackstone: false,
    ifTip: "Use half pasta, half sautéed zucchini ribbons and extra chicken.",
    ingredients: [
      { item: "chicken breast", qty: 1.25, unit: "lb", category: "meat" },
      { item: "penne pasta", qty: 12, unit: "oz", category: "pantry" },
      { item: "basil pesto", qty: 0.5, unit: "cup", category: "pantry" },
      { item: "cherry tomatoes", qty: 1, unit: "cup", category: "produce" },
      { item: "parmesan", qty: 0.5, unit: "cup", category: "dairy" },
      { item: "olive oil", qty: 1, unit: "tbsp", category: "pantry", staple: true },
    ],
    steps: [
      "Boil penne; reserve a splash of pasta water.",
      "Season and cook diced chicken in oil until golden.",
      "Toss pasta with pesto, chicken, and halved tomatoes, loosening with pasta water.",
      "Finish with parmesan.",
    ],
  },
];
